### ISSUE TITLE
Followed instructions, am unable to connect on iOS app :(

### ISSUE THREAD

**Issue by jpmcglone** [livekit-examples/swift-example#19] opened 2023-07-24 14:26 UTC
I am able to connect on https://meet.livekit.io, but not from this demo app. I get this error:

```
Disconnected

Reason: networkError(TransportError.-timedOut primary transport didn't connect)
```

Can anyone help me troubleshoot? I'm stuck.

Logs:

```
2023-07-24T10:35:22-0400 info LiveKitSDK : [] Room.connect(_:_:connectOptions:roomOptions:) connecting to room...
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Room.cleanUp(reason:isFullReconnect:) reason: nil
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.cleanUp(reason:) reason: nil
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Room.cleanUpParticipants(notify:) notify: true
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.init(connectOptions:) connectionState: disconnected(reason: nil) -> connecting, reconnectMode: nil
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.cleanUp(reason:) reason: nil
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.connect(_:_:connectOptions:reconnectMode:adaptiveStream:) reconnectMode: nil
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] MulticastDelegate<RoomDelegateObjC>.notify(label:_:) [notify] room.didUpdate connectionState: connecting oldValue: disconnected(reason: nil)
Did update connectionState disconnected(reason: nil) -> connecting
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.connect(_:_:connectOptions:reconnectMode:adaptiveStream:) Connecting with url: wss://livekit.dev.transmissionreceived.com
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.init() disconnected(reason: nil) -> connecting
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] WebSocket.session URLSessionConfiguration.timeoutIntervalForRequest: 60.0
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] WebSocket.session URLSessionConfiguration.timeoutIntervalForResource: 604800.0
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.init() connecting -> connected
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Completer<Livekit_JoinResponse>.wait(on:_:throw:) [publish] wait created...
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.restartPingTimer() ping/pong starting with interval: 10, timeout: 20
2023-07-24T10:35:22-0400 info LiveKitSDK : [] Room.signalClient(_:didReceive:) server version: 1.4.4, region: 
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] MulticastDelegate<ParticipantDelegate>.notify(label:_:) [notify] participant.didUpdate permissions: <LiveKit.ParticipantPermissions: 0x280dc8d90>
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] MulticastDelegate<RoomDelegateObjC>.notify(label:_:) [notify] room.didUpdate permissions: <LiveKit.ParticipantPermissions: 0x280dc8d90>
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Completer<Livekit_JoinResponse>.set(value:) [publish] fulfill LiveKit.Livekit_JoinResponse:
room {
  sid: "RM_TYjwRtcCpZrf"
  name: "f091126f-c1f8-4930-ad5c-3feca3ae165d"
  empty_timeout: 300
  creation_time: 1690209220
  turn_password: "MRSXS9HXxGlegN5BItyc4FiawbLoCcBRLCJe1FiC55e"
  enabled_codecs {
    mime: "audio/opus"
  }
  enabled_codecs {
    mime: "audio/red"
  }
  enabled_codecs {
    mime: "video/VP8"
  }
  enabled_codecs {
    mime: "video/H264"
  }
}
participant {
  sid: "PA_4o2Ki3qJSFsR"
  identity: "johnmcglone"
  joined_at: 1690209322
  permission {
    can_subscribe: true
    can_publish: true
    can_publish_data: true
  }
}
server_version: "1.4.4"
ice_servers {
  urls: "turn:172.98.57.78:443?transport=udp"
  urls: "turns:turn.livekit.dev.transmissionreceived.com:443?transport=tcp"
  username: "f091126f-c1f8-4930-ad5c-3feca3ae165d"
  credential: "MRSXS9HXxGlegN5BItyc4FiawbLoCcBRLCJe1FiC55e"
}
subscriber_primary: true
ping_timeout: 20
ping_interval: 10
server_info {
  version: "1.4.4"
  protocol: 9
  node_id: "ND_cGyhhAz0"
}
 func: Optional((Function))...
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
update {
  participants {
    sid: "PA_dByFXDiJY2fJ"
    identity: "johnmcglone"
    state: DISCONNECTED
    joined_at: 1690209303
    version: 3
    permission {
      can_subscribe: true
      can_publish: true
      can_publish_data: true
    }
  }
  participants {
    sid: "PA_4o2Ki3qJSFsR"
    identity: "johnmcglone"
    state: JOINED
    joined_at: 1690209322
    version: 1
    permission {
      can_subscribe: true
      can_publish: true
      can_publish_data: true
    }
  }
}

2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.configureTransports(joinResponse:) configuring transports...
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.configureTransports(joinResponse:) subscriberPrimary: true
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
refresh_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTAyMDk5MjIsImlzcyI6InByaXZhdGVLZXkiLCJuYmYiOjE2OTAyMDkzMjIsInN1YiI6ImpvaG5tY2dsb25lIiwidmlkZW8iOnsiY2FuUHVibGlzaCI6dHJ1ZSwiY2FuU3Vic2NyaWJlIjp0cnVlLCJyb29tIjoiZjA5MTEyNmYtYzFmOC00OTMwLWFkNWMtM2ZlY2EzYWUxNjVkIiwicm9vbUpvaW4iOnRydWV9fQ.h8F2gQhtZQDs8j84XpPUK_o4kucItwxgSlW-88b1L2Y"

2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
offer {
  type: "offer"
  sdp: "v=0\r\no=- 6485388205027325295 1690209322 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 7B:75:3F:92:A6:A6:FA:E9:12:47:21:69:E9:C3:07:C5:BE:FB:01:56:D7:7C:23:E2:94:28:69:0B:26:4D:2F:15\r\na=extmap-allow-mixed\r\na=group:BUNDLE 0\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=mid:0\r\na=sendrecv\r\na=sctp-port:5000\r\na=ice-ufrag:sSlogaXwobvkhYnD\r\na=ice-pwd:GjpbGsdcgVsemeQUBCiFIkKBmFiZUDgG\r\n"
}

2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
trickle {
  candidateInit: "{\"candidate\":\"candidate:28761719 1 udp 2130706431 172.98.57.78 52048 typ host\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}"
  target: SUBSCRIBER
}

2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
trickle {
  candidateInit: "{\"candidate\":\"candidate:3158683543 1 tcp 1671430143 172.98.57.78 7881 typ host tcptype passive\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}"
  target: SUBSCRIBER
}

2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
trickle {
  candidateInit: "{\"candidate\":\"candidate:28761719 1 udp 2130706431 172.98.57.78 56532 typ host\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}"
  target: SUBSCRIBER
}

2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.init(config:target:primary:delegate:reportStats:) 
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.set(reportStats:) reportStats: true
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.init(config:target:primary:delegate:reportStats:) 
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.set(reportStats:) reportStats: true
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.peerConnectionShouldNegotiate(_:) ShouldNegotiate for publisher
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.configureTransports(joinResponse:) dataChannel.Optional("_reliable") : Optional(-1)
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.configureTransports(joinResponse:) dataChannel.Optional("_lossy") : Optional(-1)
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.resumeResponseQueue() 
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Room.signalClient(_:didUpdate:) participants: [LiveKit.Livekit_ParticipantInfo:
sid: "PA_dByFXDiJY2fJ"
identity: "johnmcglone"
state: DISCONNECTED
joined_at: 1690209303
version: 3
permission {
  can_subscribe: true
  can_publish: true
  can_publish_data: true
}
, LiveKit.Livekit_ParticipantInfo:
sid: "PA_4o2Ki3qJSFsR"
identity: "johnmcglone"
state: JOINED
joined_at: 1690209322
version: 1
permission {
  can_subscribe: true
  can_publish: true
  can_publish_data: true
}
]
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.signalClient(_:didReceiveOffer:) received offer, creating & sending answer...
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Completer<Bool>.wait(on:_:throw:) [publish] wait created...
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.sendAnswer(answer:) 
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.signalClient(_:didReceiveOffer:) answer sent to signal
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didChange:) did update state connecting for subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didGenerate:) Did generate ice candidates RTC_OBJC_TYPE(RTCIceCandidate):
0
0
candidate:4258379142 1 udp 2122260223 192.168.1.250 60791 typ host generation 0 ufrag cbwh network-id 1 network-cost 10
 for subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.transport(_:didUpdate:) target: subscriber, state: connecting
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.transport(_:didGenerate:) didGenerate iceCandidate
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didGenerate:) Did generate ice candidates RTC_OBJC_TYPE(RTCIceCandidate):
0
0
candidate:358448297 1 udp 2122197247 2607:fb90:eacc:571c:bceb:c04f:da6a:9b20 49556 typ host generation 0 ufrag cbwh network-id 16 network-cost 900
 for subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.sendCandidate(candidate:target:) target: subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didGenerate:) Did generate ice candidates RTC_OBJC_TYPE(RTCIceCandidate):
0
0
candidate:2377629827 1 udp 2122129151 192.0.0.2 64735 typ host generation 0 ufrag cbwh network-id 15 network-cost 900
 for subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.transport(_:didGenerate:) didGenerate iceCandidate
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.sendCandidate(candidate:target:) target: subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.transport(_:didGenerate:) didGenerate iceCandidate
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.sendCandidate(candidate:target:) target: subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didGenerate:) Did generate ice candidates RTC_OBJC_TYPE(RTCIceCandidate):
0
0
candidate:3008514422 1 tcp 1518280447 192.168.1.250 61514 typ host tcptype passive generation 0 ufrag cbwh network-id 1 network-cost 10
 for subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didGenerate:) Did generate ice candidates RTC_OBJC_TYPE(RTCIceCandidate):
0
0
candidate:1541308505 1 tcp 1518217471 2607:fb90:eacc:571c:bceb:c04f:da6a:9b20 61516 typ host tcptype passive generation 0 ufrag cbwh network-id 16 network-cost 900
 for subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.transport(_:didGenerate:) didGenerate iceCandidate
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.sendCandidate(candidate:target:) target: subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didGenerate:) Did generate ice candidates RTC_OBJC_TYPE(RTCIceCandidate):
0
0
candidate:3274980467 1 tcp 1518149375 192.0.0.2 61517 typ host tcptype passive generation 0 ufrag cbwh network-id 15 network-cost 900
 for subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.transport(_:didGenerate:) didGenerate iceCandidate
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.sendCandidate(candidate:target:) target: subscriber
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] Engine.transport(_:didGenerate:) didGenerate iceCandidate
2023-07-24T10:35:22-0400 debug LiveKitSDK : [] SignalClient.sendCandidate(candidate:target:) target: subscriber
2023-07-24T10:35:24-0400 debug LiveKitSDK : [] ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-17", "cellular-6"], gateways: [192.168.1.1:0], activeIp: Optional("192.168.1.250")
2023-07-24T10:35:26-0400 debug LiveKitSDK : [] ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-17", "cellular-6"], gateways: [192.168.1.1:0], activeIp: Optional("192.168.1.250")
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] Room.cleanUp(reason:isFullReconnect:) reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] Engine.init(connectOptions:) connectionState: connecting -> disconnected(reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))), reconnectMode: nil
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] SignalClient.cleanUp(reason:) reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] SignalClient.init() connected -> disconnected(reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect)))
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] WebSocket.cleanUp(reason:notify:) reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] MulticastDelegate<RoomDelegateObjC>.notify(label:_:) [notify] room.didUpdate connectionState: disconnected(reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))) oldValue: connecting
Did update connectionState connecting -> disconnected(reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect)))
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] WebSocket.deinit 
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] Room.cleanUpParticipants(notify:) notify: true
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] Transport.deinit 
2023-07-24T10:35:32-0400 debug LiveKitSDK : [] Transport.deinit 
No color named 'lkRed' found in asset catalog for main bundle (/private/var/containers/Bundle/Application/29861B6F-998C-4A9C-A5AF-183EE96ED9B5/LiveKitExample.app)
```

**Comment by davidzhao** [comment] 2023-07-26 04:55
Looks like the problem is improperly configured server here.

The logs you've attached showed that the server's ICE candidates were all `172.x.x.x`, do you have `use_external_ip` set to true on the server side?

As a result, your server is returning an incorrectly mapped TURN server `turn:172.98.57.78:443?transport=udp`, also a private IP. Because of that the client cannot perform STUN and therefore is unable to connect.

It's not clear why it works on Meets though. Where is your server hosted at?

**Comment by jpmcglone** [comment] 2023-07-31 17:34
Thanks for the info. Sending this to our backend team, and I'll get back to you as soon as possible.

**Comment by jpmcglone** [comment] 2023-07-31 17:50
It's connecting from demo app now, however, the other big issue we're having is that we cannot get SDK client 1.0.13 to connect, yet 1.0.12 does. 

If you wouldn't mind looking at these logs and discerning what the issue could be (looks similar)

```
2023-07-31T13:49:46-0400 info LiveKitSDK : [] Room.connect(_:_:connectOptions:roomOptions:) connecting to room...
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Room.cleanUp(reason:isFullReconnect:) reason: nil
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.cleanUp(reason:) reason: nil
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Room.cleanUpParticipants(notify:) notify: true
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.init(connectOptions:) connectionState: disconnected(reason: nil) -> connecting, reconnectMode: nil
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.cleanUp(reason:) reason: nil
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] MulticastDelegate<RoomDelegateObjC>.notify(label:_:) [notify] room.didUpdate connectionState: connecting oldValue: disconnected(reason: nil)
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.connect(_:_:connectOptions:reconnectMode:adaptiveStream:) reconnectMode: nil
Did update connectionState disconnected(reason: nil) -> connecting
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.connect(_:_:connectOptions:reconnectMode:adaptiveStream:) Connecting with url: wss://livekit.dev.transmissionreceived.com
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.init() disconnected(reason: nil) -> connecting
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] WebSocket.session URLSessionConfiguration.timeoutIntervalForRequest: 60.0
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] WebSocket.session URLSessionConfiguration.timeoutIntervalForResource: 604800.0
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.init() connecting -> connected
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Completer<Livekit_JoinResponse>.wait(on:_:throw:) [publish] wait created...
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.restartPingTimer() ping/pong starting with interval: 10, timeout: 20
2023-07-31T13:49:46-0400 info LiveKitSDK : [] Room.signalClient(_:didReceive:) server version: 1.4.4, region: 
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] MulticastDelegate<ParticipantDelegate>.notify(label:_:) [notify] participant.didUpdate metadata: {}
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] MulticastDelegate<RoomDelegateObjC>.notify(label:_:) [notify] room.didUpdate metadata: {}
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Completer<Livekit_JoinResponse>.set(value:) [publish] fulfill LiveKit.Livekit_JoinResponse:
room {
  sid: "RM_2EXsdLqYzLPa"
  name: "40af325f-f21b-44c8-a6ea-04bfbd23d3c5"
  empty_timeout: 300
  creation_time: 1690825722
  turn_password: "e6VaEJjbuKadr6wBxUmQMsiditEFe0uWf66u9W79K6ZA"
  enabled_codecs {
    mime: "audio/opus"
  }
  enabled_codecs {
    mime: "audio/red"
  }
  enabled_codecs {
    mime: "video/VP8"
  }
  enabled_codecs {
    mime: "video/H264"
  }
}
participant {
  sid: "PA_MWMuB48WaKqe"
  identity: "926b9a84-bb54-4bd5-8eb8-5034a04041bd"
  metadata: "{}"
  joined_at: 1690825786
  permission {
    can_subscribe: true
    can_publish: true
    can_publish_data: true
  }
}
server_version: "1.4.4"
ice_servers {
  urls: "turn:192.168.100.147:443?transport=udp"
  urls: "turns:turn.livekit.dev.transmissionreceived.com:443?transport=tcp"
  username: "40af325f-f21b-44c8-a6ea-04bfbd23d3c5"
  credential: "e6VaEJjbuKadr6wBxUmQMsiditEFe0uWf66u9W79K6ZA"
}
subscriber_primary: true
ping_timeout: 20
ping_interval: 10
server_info {
  version: "1.4.4"
  protocol: 9
  node_id: "ND_9SigpZYh"
}
 func: Optional((Function))...
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] MulticastDelegate<ParticipantDelegate>.notify(label:_:) [notify] participant.didUpdate permissions: <LiveKit.ParticipantPermissions: 0x6000006fa440>
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] MulticastDelegate<RoomDelegateObjC>.notify(label:_:) [notify] room.didUpdate permissions: <LiveKit.ParticipantPermissions: 0x6000006fa440>
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.configureTransports(joinResponse:) configuring transports...
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
offer {
  type: "offer"
  sdp: "v=0\r\no=- 308358887098093654 1690825786 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 4F:8D:CF:8F:53:78:E9:80:91:A4:4D:99:5F:EF:D0:D1:09:91:80:96:16:D1:BF:E0:64:63:9D:71:92:F4:E5:24\r\na=extmap-allow-mixed\r\na=group:BUNDLE 0\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=mid:0\r\na=sendrecv\r\na=sctp-port:5000\r\na=ice-ufrag:yMlxdPliSdySagFE\r\na=ice-pwd:KYMvDPnrvPjXxrpYtooGJFlIOhebXjfX\r\n"
}

2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.configureTransports(joinResponse:) subscriberPrimary: true
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
refresh_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTA4MjYzODYsImlzcyI6InByaXZhdGVLZXkiLCJtZXRhZGF0YSI6Int9IiwibmJmIjoxNjkwODI1Nzg2LCJzdWIiOiI5MjZiOWE4NC1iYjU0LTRiZDUtOGViOC01MDM0YTA0MDQxYmQiLCJ2aWRlbyI6eyJjYW5QdWJsaXNoIjp0cnVlLCJjYW5TdWJzY3JpYmUiOnRydWUsInJvb20iOiI0MGFmMzI1Zi1mMjFiLTQ0YzgtYTZlYS0wNGJmYmQyM2QzYzUiLCJyb29tSm9pbiI6dHJ1ZX19.h0qfiNjz6ti0s3Z4ZY-3OdKNHwUGTY1La4F6Mwigx84"

2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
trickle {
  candidateInit: "{\"candidate\":\"candidate:3700605131 1 udp 2130706431 192.168.100.147 59907 typ host\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}"
  target: SUBSCRIBER
}

2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
trickle {
  candidateInit: "{\"candidate\":\"candidate:1633792299 1 tcp 1671430143 192.168.100.147 7881 typ host tcptype passive\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}"
  target: SUBSCRIBER
}

2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
trickle {
  candidateInit: "{\"candidate\":\"candidate:3916477313 1 udp 2130706431 10.42.150.0 58957 typ host\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}"
  target: SUBSCRIBER
}

2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.onWebSocketMessage(message:) Enqueueing response: LiveKit.Livekit_SignalResponse:
trickle {
  candidateInit: "{\"candidate\":\"candidate:1417921121 1 tcp 1671430143 10.42.150.0 7881 typ host tcptype passive\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}"
  target: SUBSCRIBER
}

2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Transport.init(config:target:primary:delegate:reportStats:) 
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Transport.set(reportStats:) reportStats: true
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Transport.init(config:target:primary:delegate:reportStats:) 
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Transport.set(reportStats:) reportStats: true
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Transport.peerConnectionShouldNegotiate(_:) ShouldNegotiate for publisher
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.configureTransports(joinResponse:) dataChannel.Optional("_reliable") : Optional(-1)
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.configureTransports(joinResponse:) dataChannel.Optional("_lossy") : Optional(-1)
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.resumeResponseQueue() 
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.signalClient(_:didReceiveOffer:) received offer, creating & sending answer...
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.sendAnswer(answer:) 
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.signalClient(_:didReceiveOffer:) answer sent to signal
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Completer<Bool>.wait(on:_:throw:) [publish] wait created...
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didChange:) did update state connecting for subscriber
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.transport(_:didUpdate:) target: subscriber, state: connecting
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didGenerate:) Did generate ice candidates RTC_OBJC_TYPE(RTCIceCandidate):
0
0
candidate:758795418 1 udp 2122260223 192.168.1.216 60107 typ host generation 0 ufrag 7J19 network-id 1 network-cost 10
 for subscriber
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.transport(_:didGenerate:) didGenerate iceCandidate
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.sendCandidate(candidate:target:) target: subscriber
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Transport.peerConnection(_:didGenerate:) Did generate ice candidates RTC_OBJC_TYPE(RTCIceCandidate):
0
0
candidate:1673113706 1 tcp 1518280447 192.168.1.216 63153 typ host tcptype passive generation 0 ufrag 7J19 network-id 1 network-cost 10
 for subscriber
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] Engine.transport(_:didGenerate:) didGenerate iceCandidate
2023-07-31T13:49:46-0400 debug LiveKitSDK : [] SignalClient.sendCandidate(candidate:target:) target: subscriber
2023-07-31T13:49:48-0400 debug LiveKitSDK : [] Room.signalClient(_:didUpdate:) participants: [LiveKit.Livekit_ParticipantInfo:
sid: "PA_MWMuB48WaKqe"
identity: "926b9a84-bb54-4bd5-8eb8-5034a04041bd"
state: JOINED
metadata: "{}"
joined_at: 1690825786
version: 1
permission {
  can_subscribe: true
  can_publish: true
  can_publish_data: true
}
]
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] Room.cleanUp(reason:isFullReconnect:) reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] Engine.init(connectOptions:) connectionState: connecting -> disconnected(reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))), reconnectMode: nil
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] SignalClient.cleanUp(reason:) reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] MulticastDelegate<RoomDelegateObjC>.notify(label:_:) [notify] room.didUpdate connectionState: disconnected(reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))) oldValue: connecting
Did update connectionState connecting -> disconnected(reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect)))
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] SignalClient.init() connected -> disconnected(reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect)))
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] WebSocket.cleanUp(reason:notify:) reason: Optional(LiveKit.DisconnectReason.networkError(TransportError.timedOut primary transport didn't connect))
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] Room.cleanUpParticipants(notify:) notify: true
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] WebSocket.deinit 
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] Transport.deinit 
2023-07-31T13:49:56-0400 debug LiveKitSDK : [] Transport.deinit 
No color named 'lkRed' found in asset catalog for main bundle (/Users/jpmcglone/Library/Developer/CoreSimulator/Devices/5B24B601-A03F-4143-9723-68E4D72E9A92/data/Containers/Bundle/Application/82AE6F1B-2A63-4387-B890-AE7708EB449F/LiveKitExample.app)
```

**Comment by hiroshihorie** [comment] 2023-08-22 14:18
Closing this since it looks like the issue is your server setup.

**Closed by hiroshihorie** 2023-08-22 14:18 UTC
